name: DyeOres
version: '${project.version}'
main: me.takkapi.dyeores.DyeOres
api-version: 1.21
authors: [ Takkapi ]
description: Dye any ore you want to change it
website: https://discord.gg/btX7Hv9trx
